<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class FieldMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $group = [
            [ 'description' => 'BASIC INFO',       'code' => '01' ],
            [ 'description' => 'SPOUSE INFO',      'code' => '02' ],
            [ 'description' => 'PARENT INFO',      'code' => '03' ],
            [ 'description' => 'WORK INFO',        'code' => '04' ],
            [ 'description' => 'BANK INFO',        'code' => '05' ],
            [ 'description' => 'BENEFIFIARY INFO', 'code' => '06' ],
            [ 'description' => 'GUARANTOR INFO',   'code' => '07' ],
            [ 'description' => 'REFERER INFO',     'code' => '08' ],
            [ 'description' => 'INTRODUCER INFO',  'code' => '09' ],
        ];

        DB::table('SISKOP.SYS_FIELD_GROUP')->insert($group);

        $field = [
            //CUSTOMER
            [
                'group_id'  => '01',
                'name'      => 'TITLE',
                'name2'     => 'cust_title',
                'value'     => '$customer->title_id',
                'validation'=> NULL,
                'size'      => '3',
                'type'      => 'select',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => 'App\Models\Ref\RefCustTitle',
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '01',
                'name'      => 'FULL NAME',
                'name2'     => 'custname',
                'value'     => '$customer->name',
                'validation'=> NULL,
                'size'      => '12',
                'type'      => 'text',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '01',
                'name'      => 'IDENTITY NUMBER',
                'name2'     => 'icno',
                'value'     => '$customer->icno',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'text',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'TRUE',
            ],
            [
                'group_id'  => '01',
                'name'      => 'OTHER ID',
                'name2'     => 'otheric',
                'value'     => '$customer->otheric',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'text',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'TRUE',
            ],
            [
                'group_id'  => '01',
                'name'      => 'BIRTHDATE',
                'name2'     => 'birthdate',
                'value'     => '$customer->birthdate',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'date',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '01',
                'name'      => 'BIRTHPLACE',
                'name2'     => 'birthplace',
                'value'     => '$customer->birthplace',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '01',
                'name'      => 'MOBILE NUM',
                'name2'     => 'mobile_num',
                'value'     => '$customer->birthdate',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '01',
                'name'      => 'EMAIL',
                'name2'     => 'email',
                'value'     => '$customer->email',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '01',
                'name'      => 'GENDER',
                'name2'     => 'gender',
                'value'     => '$customer->gender_id',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'select',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '01',
                'name'      => 'MARITAL',
                'name2'     => 'marital',
                'value'     => '$customer->marital_id',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'select',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '01',
                'name'      => 'RACE',
                'name2'     => 'race',
                'value'     => '$customer->race_id',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'select',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '01',
                'name'      => 'EDUCATION',
                'name2'     => 'education',
                'value'     => '$customer->education_id',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'select',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '01',
                'name'      => 'HOME ADDRESS',
                'name2'     => 'address_home',
                'value'     => '$customer->address',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],

            //PARENT
            [
                'group_id'  => '03',
                'name'      => 'FULL NAME',
                'name2'     => 'family_name',
                'value'     => '$customer->family_name',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '03',
                'name'      => 'IDENTITY NUMBER',
                'name2'     => 'family_icno',
                'value'     => '$customer->family_icno',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '03',
                'name'      => 'HOME ADDRESS',
                'name2'     => 'family_address',
                'value'     => '$customer->family_address',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '03',
                'name'      => 'MOBILE NUM',
                'name2'     => 'family_number',
                'value'     => '$customer->family_number',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '03',
                'name'      => 'EMAIL',
                'name2'     => 'family_email',
                'value'     => '$customer->family_email',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],

            //WORK
            [
                'group_id'  => '04',
                'name'      => 'COMPANY NAME',
                'name2'     => 'company',
                'value'     => '$customer->company',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '04',
                'name'      => 'NAME OF DEPARTMENT',
                'name2'     => 'department',
                'value'     => '$customer->department',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '04',
                'name'      => 'OFFICE ADDRESS',
                'name2'     => 'office_address',
                'value'     => '$customer->office_address',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '04',
                'name'      => 'POSITION',
                'name2'     => 'position',
                'value'     => '$customer->position',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '04',
                'name'      => 'OFFICE TEL NUM',
                'name2'     => 'office_number',
                'value'     => '$customer->office_number',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '04',
                'name'      => 'SALARY',
                'name2'     => 'salary',
                'value'     => '$customer->salary',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],
            [
                'group_id'  => '04',
                'name'      => 'WORKER NUMBER',
                'name2'     => 'worker_number',
                'value'     => '$customer->worker_number',
                'validation'=> NULL,
                'size'      => '6',
                'type'      => 'string',
                'pre'       => NULL,
                'post'      => NULL,
                'model'     => NULL,
                'readonly'  => 'FALSE',
            ],

        ];

        DB::table('SISKOP.SYS_FIELD_MASTER')->insert($field);
    }
}
