<h2 class="mt-6 mb-4 text-lg font-semibold border-b-2 border-gray-300">Applicant Information</h2>
<div class="grid grid-cols-1 gap-2 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3">
    <x-form.input
        label="Title"
        name="title"
        value=""
        mandatory=""
        disable=""
        type="text"
    />
    <x-form.input
        label="Name"
        name="custname"
        value=""
        mandatory=""
        disable=""
        type="text"
    />
    <x-form.input
        label="IC Number"
        name="custic"
        value=""
        mandatory=""
        disable=""
        type="text"
    />
    <x-form.input
        label="Birthdate"
        name="birthdate"
        value=""
        mandatory=""
        disable=""
        type="text"
    />
    <x-form.input
        label="Mobile Number"
        name="custic"
        value=""
        mandatory=""
        disable=""
        type="text"
    />
    <x-form.input
        label="E-Mail"
        name="email"
        value=""
        mandatory=""
        disable=""
        type="text"
    />
    <x-form.input
        label="Race"
        name="race"
        value=""
        mandatory=""
        disable=""
        type="text"
    />
    <x-form.input
        label="Gender"
        name="gender"
        value=""
        mandatory=""
        disable=""
        type="text"
    />
    <x-form.input
        label="Education"
        name="education"
        value=""
        mandatory=""
        disable=""
        type="text"
    />
    <x-form.input
        label="Marital"
        name="marital"
        value=""
        mandatory=""
        disable=""
        type="text"
    />
    <x-form.input
        label="Religion"
        name="religion"
        value=""
        mandatory=""
        disable=""
        type="text"
    />
    <x-form.input
        label="Bank"
        name="bank"
        value=""
        mandatory=""
        disable=""
        type="text"
    />
    <x-form.input
        label="Bank Account No"
        name="bank_account"
        value=""
        mandatory=""
        disable=""
        type="text"
    />
</div>